[tool.briefcase]
project_name = "Trading Contest"
bundle = "com.ak-bot.tradingcontest"
version = "0.0.1"
url = "https://www.github.com/boristown/TradingContest"
license = "MIT license"
author = 'ak-bot'
author_email = "tbziy@foxmail.com"

[tool.briefcase.app.tradingcontest]
formal_name = "Trading Contest"
description = "Trading redefine."
icon = "src/tradingcontest/resources/tradingcontest"
sources = ['src/tradingcontest']
requires = [
    'requests',
    'httpx',
    'sortedcontainers',
    'numpy',
]


[tool.briefcase.app.tradingcontest.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.tradingcontest.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.tradingcontest.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.tradingcontest.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.tradingcontest.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.tradingcontest.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.tradingcontest.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
